# Generated by Django 3.2.9 on 2021-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
